function showPhrase(){
    var frases = new Array();
    frases[0] = "Loyalty is the most important thing";
    frases[1] = "Winners make no excuses";
    frases[2] = "This is the difference between you and me, you want to lose little and I want to gain a lot";
    frases[3] = "If you have a gun pointed at your head, you pull out a bigger gun";
    frases[4] = "You don't deserve the privilege of seeing me win";
    frases[5] = "People respond to clothing";
    frases[6] = "I do not play statistics, I play the man";
    frases[7] = "I have no luck. I make my own luck";
    frases[8] = "You will never win big if you only act to minimize your failures";
    frases[9] = "Acting within the rules gets you nowhere";
    frases[10] = "Adjust your strategy based on the observation of people's emotional reactions";
    frases[11] = "If you are against the wall, break the wall";
    frases[12] = "Just because you're the newbie doesn't mean you have to think like one";
    frases[13] = "Don't advertise the problem, fix it";
    frases[14] = "It is time to trust others";
    frases[15] = "If what you earn is for vices and parties I assure you that you will never progress";
    frases[16] = "An enraged bull sees only the red mantle, not the man";
    frases[17] = "Never settle. There's always a bigger fish to catch";
    frases[18] = "The fewer things you leave to chance, the better you can control them";
    frases[19] = "Don't play with the deck, play with the man";
    frases[20] = "I have no dreams I have goals";
    frases[21] = "I do not respond to threats. I make them";
    frases[22] = "If you show you care they will think you are weak";
    frases[23] = "If you want a man to take off his coat, don't take it off. Make him feel warm and he will take it off himself.";
    frases[24] = "A scenario where you can fail? You must create a situation where that is not even a possibility. Win the impossible by rewriting the rules";
    frases[25] = "No major life decisions are made after a loss";
    frases[26] = "You live in a diluted world where you think you always win";
    frases[27] = "Being arrogant has certain benefits";
    frases[28] = "Never bow your head, always look up, whether you win or lose";
    frases[29] = "The good ones focus on the facts, the great ones only on the opponents";
    frases[30] = "Emotion is fine but it must be backed up with cold, hard facts";
    frases[31] = "Sometimes I like to be with not-so-bright people to see how they live";
    frases[32] = "I am against having emotions, not using them";
    frases[33] = "The only time success comes before work is in the dictionary";
    frases[34] = "Refuse to respond with the argument that I don't want to";
    frases[35] = "I shot you in the knee so he couldn't shoot you in the face. You're welcome";
    frases[36] = "Whoever tries to take you down is already underneath you";
    frases[37] = "Success is like when a woman is pregnant, everyone congratulates her but no one knows how many times she has tried.";
    frases[38] = "Have you ever loved someone so much that you would do anything for them? Yeah, well, become that someone and do anything for you.";
    frases[39] = "97% of the people who gave up are employed by the 3% who never gave up";
    frases[40] = "Let them hate you. Just make sure they know your name correctly";
    frases[41] = "They think you care, they will walk all over you";
    frases[42] = "Anyone can do my job, but no one can be me";
    frases[43] = "If you try, then you will fail, the verb is to do, not to try";
    frases[44] = "It's going to happen, because I'm going to make it happen";
    frases[45] = "I don't bet on probabilities, I bet on actions.I don't bet on probabilities, I bet on actions.";
    frases[46] = "Focus on improving yourself. Not on thinking you are the best.";
    frases[47] = "It's not bragging if you're telling the truth.";
    frases[48] = "Win a no-win situation by rewriting the rules";
    frases[49] = "Don't raise your voice in an argument, just improve your argument";
    frases[50] = "Do you want to change your life? Change your way of thinking";
    frases[51] = "Set such big goals for your life that you are uncomfortable telling them to small-minded people";
    frases[52] = "I like to smile at people who don't like me";
    frases[53] = "Life is a game. Play to win";
    frases[54] = "Kill them with your success. Bury them with a smile";
    frases[55] = "People respond to how we are dressed, so whether we like it or not, we should stick to that";
    frases[56] = "Loyalty is a two-way street. If I ask for it, then you'll give it to me";
    frases[57] = "Life has two rules: Never quit, Always remember rule No. 1.";
    frases[58] = "Your customer's success is your success";
    frases[59] = "You can win battles before you start them";
    frases[60] = "The law is the law, and truth is subjective.";
    frases[61] = "You will never win much if you only minimize your losses.";
    frases[62] = "When people you don't even know hate you, that's when you find out you're the best.";
    frases[63] = "When you make your goal more important than partying, welcome to the 1%.";
    frases[64] = "Don't waste your time with explanations. People only hear what they want to hear";
    frases[65] = "Winners have no excuses.";
    frases[66] = "Time is free, but it is priceless. You can't have it, but boy can you use it.";
    frases[67] = "You'd be surprised what people you trust would do when someone puts them in a position where they think they have no choice.";
    frases[68] = "Never destroy anyone in public when you can achieve the same result in private.";
    frases[69] = "If he cheated on someone else with you, he'll cheat on you with someone else.";
    frases[70] = "If you start in the last row you will not make it to the front.";



    aleatorio = Math.random() * (frases.length)
    aleatorio = Math.floor(aleatorio)

    verFrase.innerHTML = frases[aleatorio];
}